const express = require("express");
const homeroute = require("../../controllers/customercontroller/homecontroller");
const productcontroller = require("../../controllers/customercontroller/productssconstroller");
const cartcontroller = require("../../controllers/customercontroller/cartcontroller");
const checkoutcontroller = require("../../controllers/customercontroller/checkoutcontroller");
const ordercontroller = require("../../controllers/customercontroller/ordercontroller");
const profilecontroller = require("../../controllers/customercontroller/profilecontroller");
const wishlistcontroller = require("../../controllers/customercontroller/wishlistcontroller");
const reviewcontroller = require("../../controllers/customercontroller/reviewscontroller");
const customerRoute = express.Router();
customerRoute.get("/", homeroute);
customerRoute.get("/products", productcontroller);
customerRoute.get("/carts", cartcontroller);
customerRoute.get("/checkout", checkoutcontroller);
customerRoute.get("/orders", ordercontroller);
customerRoute.get("/profile", profilecontroller);
customerRoute.get("/wishlist", wishlistcontroller);
customerRoute.get("/reviews", reviewcontroller);
module.exports = customerRoute;
